### PR TITLE
Axis extensions

### PR DESCRIPTION
**Pull request by ThomasDaheim**
- added the option to set a StringConverter for number display
- added getValueForDisplay() method as in standard axis
- disabled overwriting of custom tick space values in calcAutoScale() (not a final fix but to avoid overwriting user values til solution)
- matching updates in AxisBuilder

### CODE REVIEW

**Comment by HanSolo** [comment]
Is this PR based on main or jdk17?

**Comment by HanSolo** [comment]
Could you please provide a demo in the test packages (as for the other charts) that I can use to verify the functionality? If I will merge it into master, I also need to port it to the jdk17 branch afterwards.

**Comment by ThomasDaheim** [comment]
Good point! I have it as part of my complete application but a stand-alone test case would be good... I'm offline for a few days but will have a look next week.

**Comment by HanSolo** [comment]
No Stress...I will also be on travel for some time starting from Saturday...

**Comment by HanSolo** [comment]
Added the changes from your pr to the jdk17 branch and I saw that I already implemented parts of your pr in the jdk17 branch before using the new events that I've implemented in the jdk17 branch.

**Comment by HanSolo** [comment]
No you can just go ahead for the jdk11 version, in the jdk17 version things changed a bit...I streamlined all the events I use across my different libraries and put them in separate libraries as for example jdktools, toolbox and toolboxfx. With that I can use the same events and eventhandlers when I use multiple of my libs in one project.

**Comment by ThomasDaheim** [comment]
I have extended LineChartTest to
- use a number formatter for the y-Axis
- dynamically change min/max of y-Axis to trigger rescale of the XYChart

**Comment by ThomasDaheim** [comment]
Just wanted to check if the test is OK for you? Anything else you would need to include the pull request?

I would like to release a new version of my editor with the XYChart included.

**Comment by HanSolo** [comment]
Ups…I somehow missed that…will take a look asap

**Comment by ThomasDaheim** [comment]
OK, let me try to separate things into various requests

**Comment by HanSolo** [comment]
Sorry for the inconvenience…

**Comment by ThomasDaheim** [comment]
Nope problem!

Gives me the opportunity to also add something for the missing style class in the tooltip :-) Any naming conventions, I should follow? Otherwise, it would be something like `hansolo-charts-tooltip`.

**Comment by HanSolo** [comment]
I would prefer just charts-tooltip

**Pull request closed without merging**
